const tools=[
  {
    "name": "ChatGPT",
    "category": "General Purpose / Writing",
    "description": "OpenAI's conversational AI model capable of complex reasoning, coding, and creative writing. It utilizes the GPT-4o architecture to provide multimodal interactions, allowing users to process text, audio, and images in a single thread with human-like conversational fluency.",
    "useCases": [
      "Drafting professional legal documents",
      "Writing complex SQL queries",
      "Translating colloquial idioms accurately",
      "Summarizing 100-page PDF transcripts",
      "Generating bedtime stories for children",
      "Explaining quantum physics to a toddler",
      "Creating personalized workout plans",
      "Role-playing for job interviews",
      "Debugging React.js code components",
      "Writing high-converting ad copy",
      "Analyzing sentiment in customer reviews",
      "Drafting weekly meal prep recipes",
      "Providing psychological first aid",
      "Creating travel itineraries for Tokyo",
      "Converting CSV data into JSON",
      "Writing Python automation scripts",
      "Brainstorming YouTube video ideas",
      "Answering medical trivia questions",
      "Drafting cold outreach emails",
      "Summarizing YouTube video transcripts"
    ],
    "howToUse": [
      "Go to chatgpt.com or open the mobile app",
      "Create an account or sign in with Google",
      "Select the model version (GPT-4o or GPT-3.5)",
      "Type a specific prompt in the message bar",
      "Upload files or images using the paperclip icon",
      "Press enter to generate a response",
      "Review the output for accuracy and tone",
      "Ask follow-up questions to refine results",
      "Use the 'Memory' feature to save preferences",
      "Copy or export the final text for your use"
    ],
    "features": [
      "GPT-4o multimodal reasoning",
      "Real-time voice conversation mode",
      "DALL-E 3 image generation integration",
      "Custom GPTs creation for specific tasks",
      "Advanced Data Analysis (Code Interpreter)",
      "Persistent memory across conversations",
      "Vision capabilities for image analysis",
      "Native mobile app with voice sync",
      "Multi-language support for 50+ tongues",
      "Browse with Bing web search access",
      "File upload support (PDF, DOCX, CSV)",
      "Python environment for data science",
      "API access for developers",
      "Team and Enterprise workspace tiers",
      "Privacy controls for chat history",
      "Temporary chat mode for privacy",
      "Markdown formatting for text output",
      "LaTeX support for mathematical formulas",
      "Integration with Google Drive/OneDrive",
      "Voice mode with adjustable emotional tone"
    ],
    "rating": 4.9,
    "link": "https://chatgpt.com",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg"
  },
  {
    "name": "Claude",
    "category": "Writing / Coding",
    "description": "Anthropic's flagship AI assistant focused on safety, reliability, and human-like nuance. Claude 3.5 Sonnet is renowned for its superior coding performance and sophisticated prose, offering a massive context window for large document analysis.",
    "useCases": [
      "Analyzing long-form literary manuscripts",
      "Performing complex financial audits",
      "Writing sophisticated academic essays",
      "Developing Python backends from scratch",
      "Refactoring legacy Java codebases",
      "Explaining complex legal clauses",
      "Drafting nuanced empathy-driven emails",
      "Creating detailed product specifications",
      "Comparing multiple research papers",
      "Generating creative poetry and prose",
      "Mapping architectural system diagrams",
      "Extracting structured data from images",
      "Brainstorming product naming strategies",
      "Optimizing CSS for web performance",
      "Summarizing earnings call transcripts",
      "Assisting with philosophical debates",
      "Drafting clear technical documentation",
      "Translating complex technical manuals",
      "Formatting raw data into clean tables",
      "Writing human-sounding blog articles"
    ],
    "howToUse": [
      "Visit claude.ai in your web browser",
      "Register using an email or Google account",
      "Start a new chat from the dashboard",
      "Type your query into the text input area",
      "Attach documents using the upload button",
      "Enable 'Artifacts' for code or UI previews",
      "Observe the real-time generated response",
      "Provide feedback or corrections to the AI",
      "Organize chats into labeled projects",
      "Clear or archive chats to manage history"
    ],
    "features": [
      "200k token context window support",
      "Artifacts window for side-by-side editing",
      "Claude 3.5 Sonnet high-speed reasoning",
      "Claude 3 Opus for complex logic",
      "Constitutional AI safety framework",
      "Vision and image processing capabilities",
      "Project folders for document grouping",
      "Citations for uploaded document queries",
      "JSON mode for structured data output",
      "Low hallucination rate compared to peers",
      "Human-centric writing style settings",
      "Collaborative project workspaces",
      "Advanced coding and math proficiency",
      "API availability via Anthropic Console",
      "Amazon Bedrock integration for scaling",
      "Google Cloud Vertex AI availability",
      "LaTeX rendering for science equations",
      "Interactive code execution previews",
      "Custom system prompt configurations",
      "Desktop-class web interface performance"
    ],
    "rating": 4.8,
    "link": "https://claude.ai",
    "image": "https://static.vecteezy.com/system/resources/previews/067/941/712/non_2x/claude-ai-logo-rounded-hd-free-png.png"
  },
  {
    "name": "Midjourney",
    "category": "Image Generation",
    "description": "A premier generative AI service that transforms natural language descriptions into highly detailed, artistic visuals, favored by designers for its cinematic aesthetics and high-resolution output.",
    "useCases": [
      "Generating cinematic movie posters",
      "Creating hyper-realistic product photos",
      "Designing unique logo concepts",
      "Generating character art for games",
      "Creating architectural visualizations",
      "Designing website UI backgrounds",
      "Producing textures for 3D modeling",
      "Generating book cover illustrations",
      "Creating photorealistic fashion shoots",
      "Designing interior decor concepts",
      "Generating surrealistic art pieces",
      "Creating promotional social media assets",
      "Designing patterns for textile print",
      "Producing storyboard frames for film",
      "Generating high-detail fantasy maps",
      "Creating isometric room designs",
      "Designing tattoo concepts",
      "Generating vintage-style photography",
      "Creating 8-bit pixel art characters",
      "Designing minimalistic vector-style icons"
    ],
    "howToUse": [
      "Join the Midjourney Discord server",
      "Go to a 'newbies' channel or use a bot DM",
      "Type /imagine followed by your prompt",
      "Wait for 4 image variations to generate",
      "Select U1-U4 to upscale a specific image",
      "Select V1-V4 to create variations of one",
      "Use --ar parameter to change aspect ratio",
      "Use the 'Pan' tool to extend images",
      "Use 'Vary Region' for in-painting edits",
      "Save the final image to your device"
    ],
    "features": [
      "V6 photorealism engine technology",
      "In-painting for specific object edits",
      "Out-painting for background expansion",
      "Character Consistency (--cref) tool",
      "Style Reference (--sref) feature",
      "Niji mode for anime-style generation",
      "Adjustable aspect ratios up to 2:1",
      "Multi-prompting with weight parameters",
      "Permutation prompts for bulk testing",
      "High-resolution upscalers",
      "Web-based image gallery and editor",
      "Direct Discord bot interaction",
      "Seed-based image replication",
      "Fast, Relax, and Turbo processing modes",
      "Tile feature for seamless patterns",
      "Image-to-image prompt blending",
      "Stealth mode for private generation",
      "Raw mode for less stylized output",
      "Weird parameter for eccentric results",
      "Chaos parameter for prompt variation"
    ],
    "rating": 4.9,
    "link": "https://midjourney.com",
    "image": "https://img.logo.dev/midjourney.com"
  },
  {
    "name": "ElevenLabs",
    "category": "Audio / Voice",
    "description": "A pioneer in AI audio technology, ElevenLabs offers hyper-realistic speech synthesis, voice cloning, and multilingual dubbing with emotional depth and customized vocal characteristics.",
    "useCases": [
      "Narrating audiobooks for Audible",
      "Creating voiceovers for YouTube videos",
      "Dubbing films into 29+ languages",
      "Generating NPCs voices for video games",
      "Creating personalized podcast intros",
      "Providing accessible speech for visually impaired",
      "Cloning a CEO's voice for internal memos",
      "Generating dialogue for animated films",
      "Creating realistic IVR for call centers",
      "Automating news article narration",
      "Synthesizing speech for mobile apps",
      "Creating custom GPS navigation voices",
      "Producing radio ad commercials",
      "Translating video content with lip-sync",
      "Creating meditation guide recordings",
      "Synthesizing historical figures' voices",
      "Generating content for TikTok trends",
      "Creating e-learning module audio",
      "Developing conversational AI assistants",
      "Producing high-quality sound effects"
    ],
    "howToUse": [
      "Sign up on the ElevenLabs website",
      "Navigate to the Speech Synthesis tab",
      "Choose a pre-made voice from the library",
      "Paste your text into the input box",
      "Adjust stability and clarity sliders",
      "Click Generate to hear the audio preview",
      "Download the MP3 or WAV file",
      "Use Voice Lab to clone your own voice",
      "Apply the generated audio to your project",
      "Monitor your character quota usage"
    ],
    "features": [
      "Professional Voice Cloning (PVC)",
      "Instant Voice Cloning with 60s sample",
      "Multilingual v2 for global accents",
      "Speech-to-Speech vocal transformation",
      "Text-to-Speech with emotional prosody",
      "Voice Design for unique character creation",
      "AI Dubbing with automatic lip-sync",
      "Audio Native player for websites",
      "API for real-time app integration",
      "Emotional range control",
      "Library of 1000+ community voices",
      "Non-robotic cadence",
      "Ultra-low latency generation",
      "Synthesized sound effects generation",
      "High-fidelity 44.1kHz audio output",
      "Batch conversion for long documents",
      "Project management for audiobooks",
      "Commercial usage rights for paid users",
      "Granular control over similarity",
      "Secure data encryption"
    ],
    "rating": 4.8,
    "link": "https://elevenlabs.io",
    "image": "https://upload.wikimedia.org/wikipedia/commons/e/e8/ElevenLabs_Logo_01.svg"
  },
  {
    "name": "GitHub Copilot",
    "category": "Coding",
    "description": "An AI-powered pair programmer that integrates directly into popular IDEs to provide real-time code suggestions, autocomplete functions, and natural language chat to accelerate development.",
    "useCases": [
      "Writing boilerplate unit tests",
      "Generating Python data models",
      "Refactoring complex nested loops",
      "Learning new programming frameworks",
      "Translating code from Java to Kotlin",
      "Documenting code with docstrings",
      "Creating regular expressions",
      "Writing infrastructure-as-code (Terraform)",
      "Generating React hooks and components",
      "Developing REST API endpoints",
      "Searching for bug fixes within the IDE",
      "Auto-completing repetitive CSS classes",
      "Generating Dockerfile configurations",
      "Assisting with Git commit messages",
      "Writing complex SQL join queries",
      "Optimizing algorithm performance",
      "Creating mock data for testing",
      "Integrating third-party APIs",
      "Learning Bash script commands",
      "Automating repetitive coding tasks"
    ],
    "howToUse": [
      "Subscribe to GitHub Copilot on GitHub",
      "Install the extension in VS Code",
      "Log in to your GitHub account within IDE",
      "Open a code file to begin coding",
      "Start typing a function or variable",
      "Press Tab to accept a ghost text suggestion",
      "Use Cmd+I to open the inline chat",
      "Ask questions in natural language to the bot",
      "Review and commit the generated code",
      "Check the Copilot panel for alternatives"
    ],
    "features": [
      "Real-time ghost text suggestions",
      "Natural language to code translation",
      "Copilot Chat in the IDE sidebar",
      "Context-aware code completions",
      "Support for 80+ programming languages",
      "IntelliJ and Vim integration",
      "Copilot Extensions for external tools",
      "Enterprise security filters",
      "Knowledge Base integration",
      "Automatic unit test generation",
      "Bug detection and fix suggestions",
      "Pull request summary generation",
      "Code documentation and explanation",
      "Commit message auto-generation",
      "Vulnerability filtering",
      "Mobile app support for code review",
      "CLI integration for terminal usage",
      "Organization-wide policy management",
      "Training on public open-source code",
      "Custom model fine-tuning"
    ],
    "rating": 4.7,
    "link": "https://github.com/features/copilot",
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/93/GitHub_Copilot_logo.svg"
  },
  {
    "name": "Perplexity AI",
    "category": "Search / Research",
    "description": "A conversational search engine that provides cited answers to complex queries by synthesizing information from the live web, acting as a powerful AI research assistant.",
    "useCases": [
      "Fact-checking news in real-time",
      "Synthesizing academic research topics",
      "Finding current stock market data",
      "Comparing technical product specs",
      "Generating cited bibliographies",
      "Summarizing current global events",
      "Finding local restaurant recommendations",
      "Assisting with legal case research",
      "Extracting data from scientific papers",
      "Planning travel with live flight data",
      "Checking weather and tide reports",
      "Learning new software documentation",
      "Performing competitive market analysis",
      "Generating code snippets with docs",
      "Verifying medical information (General)",
      "Finding historical dates and facts",
      "Summarizing long YouTube videos",
      "Translating phrases with context",
      "Drafting business strategy reports",
      "Searching social media trends"
    ],
    "howToUse": [
      "Visit perplexity.ai or open the app",
      "Type a question into the search bar",
      "Select 'Pro' mode for deeper research",
      "Pick a 'Focus' (e.g., Academic, YouTube)",
      "Review the summarized answer and citations",
      "Click on source links to verify facts",
      "Ask follow-up questions from the suggestions",
      "Attach files for the AI to analyze",
      "Organize searches into Collections",
      "Share the research page via link"
    ],
    "features": [
      "Real-time web crawling and indexing",
      "Direct citations for every claim",
      "Choice of models (GPT-4o, Claude 3)",
      "Collections for organizing research",
      "File upload for PDF/Text analysis",
      "Focus modes (Social, Academic, Math)",
      "Pro Search for multi-step reasoning",
      "Image generation within search results",
      "Native iOS and Android mobile apps",
      "Discover feed for trending topics",
      "Markdown export for reports",
      "API for developers",
      "Privacy-focused search",
      "Multi-language support",
      "Interactive map rendering",
      "Chrome extension for quick search",
      "Voice search capability on mobile",
      "Thread sharing with collaborative links",
      "Vision support for searching via photos",
      "Dark mode support"
    ],
    "rating": 4.8,
    "link": "https://perplexity.ai",
    "image": "https://upload.wikimedia.org/wikipedia/commons/a/a7/Perplexity_AI_logo.png"
  },
  {
    "name": "Canva Magic Studio",
    "category": "Design / Marketing",
    "description": "An all-in-one AI design suite that enables users to generate images, videos, and layouts, while offering advanced tools for photo editing and background removal.",
    "useCases": [
      "Generating Instagram posts from text",
      "Creating logo variations instantly",
      "Removing backgrounds from product photos",
      "Writing social media captions",
      "Expanding image borders with AI",
      "Translating presentations instantly",
      "Generating AI avatars for training videos",
      "Converting a blog post to a video",
      "Creating brand kits automatically",
      "Removing objects from images",
      "Designing website landing pages",
      "Generating realistic mockup images",
      "Creating personalized gift card designs",
      "Automating bulk business card creation",
      "Designing YouTube thumbnails",
      "Generating unique patterns for merch",
      "Creating animated social media ads",
      "Drafting marketing email headers",
      "Retouching portraits for LinkedIn",
      "Generating creative presentation slides"
    ],
    "howToUse": [
      "Log into your Canva account",
      "Click on 'Magic Studio' in the sidebar",
      "Choose a tool like 'Magic Design'",
      "Enter your prompt or upload a file",
      "Select from the generated templates",
      "Use 'Magic Edit' to swap objects",
      "Apply 'Magic Switch' to resize",
      "Add AI-generated text with 'Magic Write'",
      "Export the design as PNG or MP4",
      "Share directly to social media"
    ],
    "features": [
      "Magic Media (Text-to-Image)",
      "Magic Design for automated layouts",
      "Magic Edit for generative swapping",
      "Magic Expand background out-painting",
      "Magic Eraser for object removal",
      "Magic Write for copywriting",
      "Magic Switch for instant resizing",
      "Magic Morph for text effects",
      "Magic Grab for moving subjects",
      "Translate tool for multi-lingual design",
      "Beat Sync for video audio matching",
      "AI-powered Brand Voice",
      "Bulk Create from CSV data",
      "Magic Animate for motion",
      "Content Planner for social",
      "Integrated Stock Image library",
      "Real-time team collaboration",
      "Mobile app synchronization",
      "Vector graphic editing support",
      "Custom branding uploads"
    ],
    "rating": 4.7,
    "link": "https://canva.com",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/08/Canva_icon_2021.svg"
  },
  {
    "name": "Descript",
    "category": "Audio / Video Editor",
    "description": "A video and podcast editor that works like a word processor. It transcribes media into text, allowing users to edit video by simply deleting or moving text.",
    "useCases": [
      "Editing podcasts by deleting text",
      "Removing filler words (um, uh) instantly",
      "Generating AI voiceovers via Overdub",
      "Creating social media video audiograms",
      "Transcribing Zoom meeting recordings",
      "Cloning your own voice for retakes",
      "Adding auto-captions to social videos",
      "Recording high-quality screen shares",
      "Editing YouTube videos via transcript",
      "Applying studio sound to low-quality mic",
      "Generating chapters for long videos",
      "Translating video subtitles automatically",
      "Removing background noise from audio",
      "Creating video sales letters (VSLs)",
      "Collaborating with teams on video drafts",
      "Replacing video backgrounds",
      "Fixing eye contact with AI",
      "Adding background music with ducking",
      "Generating summaries for audio files",
      "Formatting transcripts for blog posts"
    ],
    "howToUse": [
      "Download and install the Descript app",
      "Create a new project and import media",
      "Wait for the automatic transcription",
      "Highlight and delete text to cut audio",
      "Use 'Remove Filler Words' from the menu",
      "Apply 'Studio Sound' for better audio",
      "Add captions using the 'T' icon",
      "Use 'Overdub' to fix speaking errors",
      "Export the final video or audio file",
      "Publish directly to YouTube or Spotify"
    ],
    "features": [
      "Text-based video/audio editing",
      "Automatic high-accuracy transcription",
      "Studio Sound AI audio enhancement",
      "Filler word removal (one-click)",
      "Overdub AI voice cloning",
      "Eye Contact AI video adjustment",
      "Green Screen background removal",
      "Dynamic automatic captions",
      "Multi-track editing support",
      "Remote recording for podcasts",
      "Screen recording with cam bubble",
      "Social media template library",
      "Stock media assets",
      "AI Summaries and show notes",
      "Audio-to-Video audiogram generator",
      "Collaborative cloud editing",
      "Export to Premiere/Final Cut",
      "Multiple speaker identification",
      "Custom branding for captions",
      "Low-latency cloud processing"
    ],
    "rating": 4.8,
    "link": "https://descript.com",
    "image": "https://upload.wikimedia.org/wikipedia/commons/d/d3/Descript_%28Icon%29.svg"
  },
  {
    "name": "Jasper AI",
    "category": "Marketing / Writing",
    "description": "An enterprise-grade AI marketing platform designed to maintain brand voice across blog posts, ads, and emails while offering SEO optimization.",
    "useCases": [
      "Writing 2,000-word SEO blog posts",
      "Generating high-converting Facebook ads",
      "Crafting brand-aligned email sequences",
      "Creating product descriptions for Amazon",
      "Generating LinkedIn thought-leadership posts",
      "Brainstorming marketing campaign hooks",
      "Developing video scripts for TikTok",
      "Translating marketing copy to 25+ languages",
      "Summarizing long-form whitepapers",
      "Improving existing copy for clarity",
      "Writing press releases for launches",
      "Generating catchy headlines for websites",
      "Creating FAQ sections for landing pages",
      "Drafting internal newsletters",
      "Writing creative stories for mascots",
      "Analyzing competitor marketing copy",
      "Repurposing webinars into blog posts",
      "Optimizing content for keywords",
      "Generating cold outreach scripts",
      "Creating consistent style guides"
    ],
    "howToUse": [
      "Sign up for a Jasper account",
      "Set up your Brand Voice and Knowledge Base",
      "Choose a template from the library",
      "Input your topic and target keywords",
      "Hit 'Generate' to see the draft",
      "Use the 'Remix' tool to change tone",
      "Check SEO scores with integration",
      "Edit the text in the document editor",
      "Run the plagiarism checker for safety",
      "Publish or export to your CMS"
    ],
    "features": [
      "Brand Voice training and application",
      "50+ marketing copy templates",
      "Long-form document editor",
      "Surfer SEO integration",
      "Jasper Campaigns multi-asset generation",
      "Knowledge Base for company facts",
      "Chrome browser extension",
      "Plagiarism checker",
      "Multi-language translation (25+)",
      "AI Art generation within editor",
      "Team collaboration permissions",
      "API for enterprise integration",
      "Grammarly integration built-in",
      "Dynamic content variables",
      "Content repurposing workflows",
      "Marketing specific recipes",
      "Customizable workspace dashboards",
      "Secure enterprise data handling",
      "Real-time collaboration cursors",
      "One-click formatting"
    ],
    "rating": 4.6,
    "link": "https://jasper.ai",
    "image": "https://img.logo.dev/jasper.ai"
  },
  {
    "name": "Grammarly",
    "category": "Writing",
    "description": "A sophisticated writing assistant that offers real-time suggestions for grammar, tone, clarity, and conciseness across web and desktop apps.",
    "useCases": [
      "Polishing professional emails",
      "Ensuring academic essay integrity",
      "Correcting grammar in Slack messages",
      "Improving clarity in technical reports",
      "Adjusting tone for sensitive HR news",
      "Detecting plagiarism in student papers",
      "Shortening wordy sentences",
      "Correcting punctuation in manuscripts",
      "Enhancing vocabulary in creative writing",
      "Consistency checking for brand terms",
      "Translating non-native English writing",
      "Formatting citations accurately",
      "Correcting common spelling mistakes",
      "Improving LinkedIn descriptions",
      "Drafting clear project proposals",
      "Refining customer support responses",
      "Optimizing blog posts for readability",
      "Checking grammar in Google Docs",
      "Ensuring professional tone on social",
      "Correcting typos in real-time"
    ],
    "howToUse": [
      "Download Grammarly for Desktop",
      "Install the mobile keyboard app",
      "Log in or create a free account",
      "Open any text document or email",
      "Notice the underlined suggestions",
      "Click a suggestion to see explanation",
      "Accept the change by clicking it",
      "Set your 'Goals' for tone and audience",
      "Check the 'Clarity' and 'Engagement' tabs",
      "Review the final 'Score' for your writing"
    ],
    "features": [
      "Real-time grammar and spell check",
      "AI Tone Detector and adjuster",
      "Plagiarism checker",
      "Generative AI writing (GrammarlyGO)",
      "Style and clarity suggestions",
      "Conciseness reduction",
      "Citation generator and formatter",
      "Personal dictionary for custom terms",
      "Weekly writing progress reports",
      "Multi-platform support",
      "Google Docs and MS Word integration",
      "Browser extension for all websites",
      "Enterprise security and privacy",
      "Team style guide enforcement",
      "Knowledge share for business teams",
      "Sentence structural improvements",
      "Punctuation and preposition check",
      "Vocabulary enhancement suggestions",
      "Goal setting for audiences",
      "Real-time feedback on mobile"
    ],
    "rating": 4.8,
    "link": "https://grammarly.com",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0c/Grammarly_logo.svg"
  },
  {
    "name": "Runway",
    "category": "Video Generation",
    "description": "Runway allows users to generate, edit, and manipulate video content using text, images, or existing clips with high-end cinematic quality.",
    "useCases": [
      "Generating cinematic video from text",
      "Transforming images into animations",
      "Replacing video backgrounds",
      "Removing objects from video",
      "Generating slow-motion from normal clips",
      "Creating consistent video styles",
      "Generating textures for 3D environments",
      "Producing AI-driven music videos",
      "Expanding video borders (Out-painting)",
      "Generating realistic human motion",
      "Creating surreal dream-like sequences",
      "Upscaling low-resolution video",
      "Color grading video with text prompts",
      "Generating custom LUTs for editors",
      "Synthesizing high-detail landscapes",
      "Animating portraits for social media",
      "Creating seamless video loops",
      "Designing VFX for short films",
      "Prototyping video concepts for ads",
      "Generating unique motion graphics"
    ],
    "howToUse": [
      "Sign up on the RunwayML website",
      "Select 'Gen-3 Alpha' or 'Gen-2' from tools",
      "Enter a descriptive text prompt",
      "Upload a reference image for style",
      "Adjust 'Motion' and 'Style' settings",
      "Click 'Generate' to create a clip",
      "Use 'Multi-Motion Brush' for local edits",
      "Review the generated video preview",
      "Export the high-definition video file",
      "Combine clips in the built-in editor"
    ],
    "features": [
      "Gen-3 Alpha text-to-video engine",
      "Gen-2 image-to-video generation",
      "Multi-Motion Brush for local control",
      "Advanced Camera Motion controls",
      "Director Mode for specific angles",
      "Video In-painting for object removal",
      "Green Screen background replacement",
      "Frame Interpolation (Super slow-mo)",
      "High-resolution 4K video upscaler",
      "Custom Model training",
      "Lip Sync for talking heads",
      "Asset management for projects",
      "Collaboration tools for teams",
      "Integrated full video editor",
      "Real-time generative video preview",
      "Mobile app generation",
      "Text-to-Image generation",
      "Audio generation and transcription",
      "Subtitles and caption automation",
      "Commercial usage licenses"
    ],
    "rating": 4.7,
    "link": "https://runwayml.com",
    "image": "https://img.logo.dev/runwayml.com"
  },
  {
    "name": "Zapier Central",
    "category": "Automation",
    "description": "An AI-driven workspace from Zapier that allows users to build, teach, and chat with AI agents that can access 6,000+ app integrations.",
    "useCases": [
      "Automating customer support replies",
      "Summarizing Slack threads into Jira tickets",
      "Qualifying leads from Typeform entries",
      "Managing complex project calendars",
      "Drafting social media posts from news",
      "Updating CRM records via chat",
      "Analyzing sales data from spreadsheets",
      "Sending personalized cold email replies",
      "Automating invoice processing tasks",
      "Coordinating meeting times with clients",
      "Scraping web data into Google Sheets",
      "Generating weekly team reports",
      "Researching prospects on LinkedIn",
      "Managing e-commerce inventory alerts",
      "Translating incoming support tickets",
      "Assigning tasks based on email priority",
      "Monitoring brand mentions on Twitter",
      "Cross-posting blog content to social",
      "Summarizing PDF invoices for accounting",
      "Executing custom Python automation code"
    ],
    "howToUse": [
      "Login to Zapier and open Central",
      "Create a new AI Agent",
      "Connect your favorite apps",
      "Teach the agent by chatting with it",
      "Set up 'Behaviors' (Triggers and Actions)",
      "Provide a knowledge base (PDFs/URLs)",
      "Test the agent's logic in the preview",
      "Deploy the agent as a bot or sidebar",
      "Monitor agent activity in the log",
      "Refine instructions based on performance"
    ],
    "features": [
      "Interactive AI Agent builder",
      "Access to 6,000+ app integrations",
      "Custom knowledge base uploads",
      "Natural language teaching interface",
      "Event-driven automation triggers",
      "Persistent agent memory",
      "Live testing and debugging console",
      "Collaborative agent sharing",
      "No-code logic and branching",
      "Integration with OpenAI/Anthropic",
      "Multi-step reasoning capabilities",
      "Action-oriented task execution",
      "Activity auditing and logging",
      "Variable and data mapping",
      "Secure API key management",
      "Agent personalities and tone",
      "Deployment via Chrome Extension",
      "Integration with Zapier Tables",
      "Web research and browsing ability",
      "Real-time data synchronization"
    ],
    "rating": 4.6,
    "link": "https://zapier.com/central",
    "image": "https://img.logo.dev/zapier.com"
  }
]